minio:
  endPoint: http://47.103.22.99:9000
  accessKey: admin
  secretKey: 12345678
server:
  port: 8000
spring:
  application:
    name: file-client
  datasource:
    url: jdbc:mysql://47.103.22.99:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
     defaultZone: http://47.103.202.218:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
