server:
  port: 8763
spring:
  application:
    name: user-client
  datasource:
    url: jdbc:mysql://47.103.22.99:3306/oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://47.103.202.218:8761/eureka
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml