spring:
  application:
    name: auth-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.22.99:3306/oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /uaa
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://47.103.202.218:8761/eureka