server:
  port: 8762
spring:
  application:
    name: product-client
  datasource:
    url: jdbc:mysql://47.103.22.99:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.103.202.218
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: 3000
        max-idle: 8
eureka:
  client:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

